config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  get 'dashboard', to: 'dashboard#index'
  get 'products/:id', to: 'products#show', as: :products_details
  post 'products/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/api_log.rb
class ApiLog < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :variants

  def self.create_many products
    valid_products = products.select {|product| self.is_valid?(product)}.map {|product| {
      name: product['name'],
      description: product['description'],
      variants: product['variants'].select {|variant| Variant.is_valid?(variant)}
    }}

    return unless valid_products.length > 0

    products = Product.insert_all(valid_products.map {|product| { 
      name: product[:name], 
      description: product[:description], 
      created_at: DateTime.now,
      updated_at: DateTime.now
    }}).rows.flatten

    Variant.insert_all(valid_products.each_with_index.map {|vp, i| vp[:variants].map {|variant| { 
      name: variant['name'], 
      price: variant['price'],
      product_id: products[i],
      created_at: DateTime.now,
      updated_at: DateTime.now
    }}}.flatten)
  end

  def self.is_valid? product
    !product['name'].blank? and 
      !product['description'].blank? and 
      (product['variants'] || []).select {|variant| Variant.is_valid?(variant)}.length > 0
  end
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product

  def self.is_valid? variant
    !variant['name'].blank? and variant['price'] > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @attempted_products = ApiLog.sum(:quantity)
    @valid_products = Product.count

    @title = I18n.t('dashboard.title')
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by_id(params[:id])

    return redirect_to root_path if @product.nil?

    @title = @product.name
  end

  def create
    products = JSON.parse(request.body.read)
    
    ApiLog.create(quantity: products.length)

    return render json: { success: false }, status: :payload_too_large unless products.length <= 10000
    
    Product.create_many(products)
    render json: { success: true }, status: :created
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<div class="kpi-container">
    <div class="kpi-item">
        <h2><%= @attempted_products %></h2>
        <p><%= t('dashboard.total_products') %></p>
    </div>
    <div class="kpi-item">
        <h2><%= @valid_products %></h2>
        <p><%= t('dashboard.success_products') %></p>
    </div>
    <div class="kpi-item">
        <h2><%= (@attempted_products - @valid_products) %></h2>
        <p><%= t('dashboard.failed_products') %></p>
    </div>
</div>

app/views/layouts/_menu.html.erb
<div class="main-menu">
  <%= link_to t('products.title'), root_path, class: "main-menu-item#{current_page?(root_path) ? ' active' : ''}" %>
  <%= link_to t('dashboard.title'), dashboard_path, class: "main-menu-item#{current_page?(dashboard_path) ? ' active' : ''}" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plist <%= @title.blank? ? '' : "- #{@title}" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/menu" %>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="products-container">
    <% @products.each do |product| %>
        <div class="product-item">
            <div>
                <h3 class="product-title"><%= product.name %></h3>
                <%= link_to t('products.show_details'), products_details_path(id: product.id) %>
            </div>
            <p class="product-description"><%= product.description %></p>
        </div>    
    <% end %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= @product.description %></p>

<table>
    <thead>
        <tr>
            <th><%= t('products.variant') %></th>
            <th><%= t('products.price') %></th>
        </tr>
    </thead>
    <tbody>
        <% @product.variants.each do |variant| %>
            <tr>
                <td><%= variant.name %></td>
                <td><%= number_to_currency(variant.price) %></td>
            </tr>
        <% end %>
    </tbody>
</table>